### ISSUE TITLE
Aggiungere https://calendar.students.cs.unibo.it/

### ISSUE THREAD

**Issue by VaiTon** [csunibo/wiki#2]

**Comment by foxyseta** [comment]
Ho aggiunto una pagina vuota qui: https://github.com/csunibo/wiki/blob/main/content/applicativi-web/calendario.md

Visto che ci hai lavorato tu, ti andrebbe di completarla a piacere? Qualsiasi cosa che pensi sarà utile quando tu ti sarai laureato va più che bene.

**Comment by VaiTon** [comment]
Fatto in ce24ad0
