### ISSUE TITLE
Aggiungere una pagina dedicata al modello Typst

### ISSUE THREAD

**Issue by foxyseta** [csunibo/wiki#7]
@cristian-5 prendendo ispirazione dalle altre pagina sulla Wiki per i modelli di tesi, dovresti farne una anche per documentare Typst. Ricorda che il README di Typst deve puntare a tale pagina.

**Comment by cristian-5** [comment]
forse non è necessario in quanto la documentazione di Typst è estremamente semplice ed esaustiva.

**Comment by foxyseta** [comment]
La wiki serve anche come elenco dei servizi offerti da csunibo (il readme su github non è pensato per essere esaustivo). Puoi anche solo mettere la pagina con una sola frasetta e i llink alla documentazione typst se ê fatta così bene.

**Comment by foxyseta** [comment]
@cristian-5 bump. Anche una cosa molto molto semplice è sufficiente.

**Comment by foxyseta** [comment]
Risolto in f602567
